name: overfit

wandb:
    mode: dryrun
    name: test
    project: soft_flow
model:
    three_frames: false
    weight_sl: 61 #61 #933
    downsample_factor: 4 #4 #32
    filter_zoom: 1 #4
    smoothness: 1.5e-1 # 2.5e-1 is optimal
    pos_smoothness: 3e-2 
    temp_smoothness: 0.0
    frameskip: 1
    norm: 0.0
    entropy: 0.0 #1e2
    cost_method: feats #weights 
    feat_dim: 12 #15 #32 #28 #128
    temp: 0.
    temp_scheduling: false 
    charbonnier_flatness: 0.0 #1e-1
    bisided: true
    fft_filter: butter #rect
    fft: 1e-1 #65,95 #17,24 #65,95 # 127 189
dataset:
    dataset: llff #llff #sintel 
    split: validation
    idx: 27 #14 #27 #0
    imsz: 252,189 #252,189 #128,128 #240,135 #64,27
    imsz_super: 1008,756 #1008,756 #512,512 #4032,3024 #1920,1080 #4032,3008 #2016,1516
    subset: horns
training:
    precision: 32
    data:
        batch_size: 1
        shuffle: false
    overfit_batch: 1
    lr: 5e-1
    weight_decay: 0.0
validation:
    check_epoch: 50
    limit_batch: 1
    check_interval: 1
    data:
        batch_size: 1
        shuffle: false
