name: overfit

wandb:
    mode: dryrun
    name: test
    project: soft_flow
model:
    three_frames: false
    weight_sl: 31 #61 #933
    downsample_factor: 1 #4 #32
    filter_zoom: 1 #4
    smoothness: 2e-1 #1e-1 # 6e-1
    pos_smoothness: 0 #2e-2 
    frameskip: 1
    norm: 0.0
    entropy: 0.0 #1e2
    cost_method: nn #feats #weights 
    feat_dim: 40 #32 #28 #128
    temp: 9 # set this to 9 if no temp scheduling
    temp_scheduling: false # set temp=3 (or something low) to begin with 
    charbonnier_flatness: 0.0 #1e-1
    bisided: false
dataset:
    dataset: sintel #llff #sintel
    train_split: training
    idx: 0 #27 #0 #27 #14
    imsz: 1024,436 #336,252 #512,224 #252,189 #128,128 #240,135 #64,27
    imsz_super: 1024,436 #1008,756 #1024,448 #1008,756 #1008,756 #512,512 #4032,3024 #1920,1080 #4032,3008 #2016,1516
    subset: horns
    augmentations:
        random_crop: true
        color: false
    flow_max: 15
training:
    precision: 32
    data:
        batch_size: 2
        shuffle: true
    overfit_batch: 0.0
    lr: 2e-4 # dust3r LR
    weight_decay: 0.0
    #accumulate: 2
validation:
    check_epoch: 5
    limit_batch: 4
    check_interval: 140
    data:
        batch_size: 2
        shuffle: false
