name: overfit

wandb:
    mode: dryrun
    name: test
    project: soft_flow
    entity: califyn
model:
    three_frames: true
    weight_sl: 31
    downsample_factor: 1
    filter_zoom: 1
    smoothness: 2.5e-1
    smoothness_edge: 0.0
    pos_smoothness: 0.0 #3e-2
    temp_smoothness: 0.0 #3e-1
    temp_on_occ: false #true
    frameskip: 1
    norm: 0.0
    entropy: 0.0 #1e2
    feat_dim: 32 #12 #32 #28 #128
    temp: 9 #0.1
    temp_scheduling: false 
    charbonnier_flatness: 0.0 #1e-1
    bisided: false
    bisided_alternating: false
    fft_filter: null #butter #rect
    fft: 1e-1 #65,95 for rect
    border_handling: null #NNFIX pad_feats #fourth_channel #pad_feats
    border_handling_on: -1 #10000000
cost:
    method: feats #nn NNFIX
    model: null #croco_dpt NNFIX
    pred_occ_mask: null 
dataset:
    dataset: sintel
    train_split: validation
    val_split: validation
    idx: 0
    imsz: 1 
    imsz_super: 1
    dstype: clean
    augmentations:
        random_crop: false
        color: false
    flow_max: 15
    crop_to: 224,224
    use_feats: self #unet #implicit #identity
    num_workers: 0
training:
    precision: 32
    data:
        batch_size: 1
        shuffle: true
    overfit_batch: 1
    lr: 5e-1 #2e-5 NNFIX
    high_lr: 5e-1 # 3e-4 NNFIX
    high_lr_steps: -1 #1000
    temp_lr: 3e-4 #5e-2
    weight_decay: 0.
    ckpt_every: 1500 #12500
validation:
    check_epoch: 50
    limit_batch: 1
    check_interval: 1
    full_val_every: null #100
    data:
        batch_size: 1
        shuffle: false
