name: overfit

wandb:
    mode: dryrun
    name: test
    project: soft_flow
    resume: 7x50j66n
    use_new_id: true
    entity: califyn
model:
    three_frames: false
    weight_sl: 31
    downsample_factor: 4
    filter_zoom: 1
    smoothness: 2.5e-1
    pos_smoothness: 3e-2
    temp_smoothness: 0.0
    frameskip: 1
    norm: 0.0
    entropy: 0.0 #1e2
    feat_dim: 32 #12 #32 #28 #128
    temp: 9 #0.1
    temp_scheduling: false 
    charbonnier_flatness: 0.0 #1e-1
    bisided: true
    bisided_alternating: false
    fft_filter: null #butter #rect
    fft: 1e-1 #65,95 for rect
    border_handling: null #fourth_channel #pad_feats
cost:
    method: nn
    model: croco
dataset:
    dataset: sintel
    train_split: validation #training 
    idx: 0 
    imsz: 4 
    imsz_super: 1
    imsz_div: 16
    dstype: clean
    augmentations:
        random_crop: true
        color: false
    flow_max: 15
    crop_to: 96,256 #null #224,224
training:
    precision: 32
    data:
        batch_size: 1
        shuffle: true
    overfit_batch: 0.0 #1 # 0.0 to turn off
    lr: 1e-4 
    temp_lr: 0 #5e-2
    weight_decay: 0.0
    ckpt_every: 50000
validation:
    check_epoch: 25
    limit_batch: 16 
    check_interval: 28
    full_val_every: null
    data:
        batch_size: 1
        shuffle: false
