name: overfit

wandb:
    mode: dryrun
    name: test
    project: soft_flow
model:
    three_frames: false
    weight_sl: 31
    downsample_factor: 1
    filter_zoom: 1
    smoothness: 2.5e-1
    pos_smoothness: 3e-2
    temp_smoothness: 0.0
    frameskip: 1
    norm: 0.0
    entropy: 0.0 #1e2
    feat_dim: 18 #12 #32 #28 #128
    temp: 0.1
    temp_scheduling: false 
    charbonnier_flatness: 0.0 #1e-1
    bisided: true
    fft_filter: null #butter #rect
    fft: 1e-1 #65,95 for rect
cost:
    method: nn
    model: croco
dataset:
    dataset: sintel
    train_split: validation 
    idx: 0 
    imsz: 1 
    imsz_super: 1
    dstype: clean
    augmentations:
        random_crop: false
        color: false
    flow_max: 15
    crop_to: 224,224
training:
    precision: 32
    data:
        batch_size: 1
        shuffle: true
    overfit_batch: 1 # 0.0 to turn off
    lr: 4e-4
    weight_decay: 0.0
validation:
    check_epoch: 50
    limit_batch: 1
    check_interval: 1
    data:
        batch_size: 1
        shuffle: false
